spring.application.name=cloud
spring.datasource.url=jdbc:postgresql://localhost:5433/projet_cloud_s5
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Firebase Configuration
firebase.apiKey=AIzaSyBuiUJBK9_eEXVKjc89iUNn1gLHdrcqwQk

# Mode de fonctionnement: ONLINE (Firebase par defaut) | OFFLINE (Local par defaut) | AUTO (detecte la connexion)
app.mode=AUTO

# Security parameters are stored in the 'parametres' database table.
