spring.application.name=cloud
spring.datasource.url=jdbc:postgresql://localhost:5433/projet_cloud_s5
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
