spring.application.name=cloud
spring.datasource.url=jdbc:postgresql://localhost:5433/projet_cloud_s5
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
firebase.apiKey=AIzaSyBuiUJBK9_eEXVKjc89iUNn1gLHdrcqwQk
firebase.authUrl=https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=
firebase.registerUrl=https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=
jwt.secret=votre_super_cle_secrete_de_32_caracteres_minimum_pour_hs256
APP_ROLE=USER,USER_MOBILE,MANAGER,MANAGER_WEB
